language: python
python:
  - "3.6"

# installing additional dependencies
# before_install:
#   - sudo apt-get -qq -y update
#   - sudo apt-get -qq install nvidia-cuda-toolkit

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
# script: pytest
script: "python run_unit_tests.py -n 1000"

# blocklist
branches:
  except:
  - /^develop-.*$/

# safelist
branches:
  only:
  - develop
  - master

# maybe this won't be useful
# sudo: false

# specify how much commits to store in travis
git:
  depth: 3

# for telegram notifications
notifications:
  email:
    recipients:
      - dmdesk1@gmail.com
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: change
    on_error: always

  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify?secret=What's going to be then, yeah?
    on_success: change
    on_failure: always
    on_start: change
    on_cancel: always
    on_error: always
